// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#include <hardware/clocks.h>
#endif

#define PIO_CLOCK pio0
#define SM_CLOCK 1

#define FREQ ((2*1100 * KHZ)) // 1.100

// #define CLOCK_PIO_PIN (17)

// ----- //
// clock //
// ----- //

#define clock_wrap_target 0
#define clock_wrap 1

static const uint16_t clock_program_instructions[] = {
            //     .wrap_target
    0xa042, //  0: nop                    side 0     
    0x1000, //  1: jmp    0               side 1     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program clock_program = {
    .instructions = clock_program_instructions,
    .length = 2,
    .origin = -1,
};

static inline pio_sm_config clock_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + clock_wrap_target, offset + clock_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void clock_program_init(PIO pio, uint sm, uint offset, uint pin, float freq) {
    pio_sm_config c = clock_program_get_default_config(offset);
    // Map the state machine's OUT pin group to one pin, namely the `pin`
    // parameter to this function.
    sm_config_set_out_pins(&c, pin, 1);
    // Set this pin's GPIO function (connect PIO to the pad)
    pio_gpio_init(pio, pin);

    sm_config_set_sideset_pins(&c, pin);
    // Set the pin direction to output at the PIO
    pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
    // Load our configuration, and jump to the start of the program
    pio_sm_init(pio, sm, offset, &c);

    // pio_sm_set_clkdiv(pio, sm, 100000.0 / 2);
    pio_sm_set_clkdiv(pio, sm, clock_get_hz(clk_sys) / (2 * freq ));

    // Set the state machine running
    pio_sm_set_enabled(pio, sm, true);
}

#endif

static inline void init_clock_pio(PIO pio,uint sm,uint pin, float freq) {

    uint offset = pio_add_program(pio, &clock_program);
    clock_program_init(pio,sm,offset,pin,freq);

}

// Динамическое изменение частоты PIO на лету
static inline void change_clock_frequency(PIO pio, uint sm, float freq) {
    // Останавливаем state machine
    pio_sm_set_enabled(pio, sm, false);

    // Устанавливаем новый делитель частоты
    pio_sm_set_clkdiv(pio, sm, clock_get_hz(clk_sys) / (2 * freq));

    // Запускаем state machine снова
    pio_sm_set_enabled(pio, sm, true);
}